### PR TITLE
Updated for Swift 3 changes

### PR DESCRIPTION
**Pull request by shnhrrsn**

### CODE REVIEW

**Comment by davecom** [comment]
Hi Shaun, thanks for the contribution! Can you put this in a new Swift3 branch?

**Comment by shnhrrsn** [comment]
This should be backwards compatible with swift 2, I was hoping to get into master for SPM support

**Comment by davecom** [comment]
Okay - I understand - I'll take a look today. Thanks!

**Comment by davecom** [comment]
Looks good, thanks for the contribution!

**Pull request merged**
