### PR TITLE
Set watchOS deployment target to 2.0

### PR DESCRIPTION
**Pull request by halileohalilei**
I just added a single line to the .podspec file to support watchOS platform. I'm not sure if this is enough for the support, can you kindly check and accept my pull request if so.

### CODE REVIEW

**Comment by davecom** [comment]
Hi @halileohalilei ,
I don't see anything that should be stopping SwiftPriorityQueue from working on watchOS. I don't use CocoaPods with watchOS, so I can't speak to that. However, the library only uses the Swift standard library, so there's no reason it should be incompatible. Further, if CocoaPods is not doing the trick, you can just include the single `SwiftPriorityQueue.swift` file directly. Thanks for the contribution.

**Comment by halileohalilei** [comment]
Thank you, could you also release it as a new version so that I can use it with my watchOS apps?

**Comment by davecom** [comment]
Sure, I'll do that when I get a chance this weekend. Thanks for letting me know.

**Comment by davecom** [comment]
@halileohalilei It should be updated now (version 1.1.2). Good luck.

**Comment by halileohalilei** [comment]
Thank you so much for the fast response, cheers!

**Comment by halileohalilei** [comment]
@davecom I'm really sorry to bother you again, but could you also update the version on [the master Specs repo](https://github.com/CocoaPods/Specs?) I have CI in my project and when `pod spec lint` is run, I get an error saying that SwiftPriorityQueue does not support watchOS 2.0, since it tries to lint using the .podspec file on the master repo for every dependency.

**Comment by davecom** [comment]
@halileohalilei Sorry about that. I forgot to push to trunk the other day. It should be updated now. Let me know if there are any further issues.

**Comment by halileohalilei** [comment]
Everything works perfectly now, thank you!

**Pull request merged**
